config/routes.rb
Rails.application.routes.draw do

  get 'home/Home'

  devise_for :users
  resources :links
  resources :campaigns
  get 'users/index'
  root 'links#index'
  get 'pages/contact'
  get 'pages/home'
  get 'pages/how'
  get 'pages/oops'
  get 'pages/notyours'
  get 'pages/list'
  get 'pages/help'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  belongs_to :user


end

app/models/link.rb
class Link < ActiveRecord::Base

  extend FriendlyId
  friendly_id :product, use: :slugged

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :storage => :dropbox,
      :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
  validates :url, presence: true

  def should_generate_new_friendly_id?
  new_record? || slug.blank?
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :website, presence: true

  has_many :campaigns, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :website
    devise_parameter_sanitizer.for(:account_update) << :website
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def new
    @campaign = Campaign.new
  end

  def create
    #Destroy Links

    #Create Campaign
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id

    if @campaign.save
      redirect_to @campaign
    else
      render 'new'
    end

  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    redirect_to campaigns_path
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :product, :website, :productlink, :description, :date, :title)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all.order("created_at DESC")
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.save
  end

  def show
      @link = Link.friendly.find(params[:id])

      if user_signed_in?

      else
        redirect_to "/pages/oops"
      end
  end

  def edit
    @link = Link.friendly.find(params[:id])

    @link.id = @link.title

  end

  def update
    @link = Link.friendly.find(params[:id])

    if @link.update(link_params)
      redirect_to @link
    else
      render 'edit'
    end

  end

  def destroy
    @link = Link.friendly.find(params[:id])

    @link.destroy
    redirect_to root_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :description, :image, :product, :cheese)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campaigns/index.html.erb
<html>
  <head>

  </head>
  <body>
    <h1 class="blue text-center lighter">Your Account</h1>
    <p>Your Email: <%= current_user.email %></p>
    <p>Your Website: <%= link_to current_user.website, current_user.website, class: "btn-link", target: "_blank" %></p>

    <br>

    <h2 class="lighter">Your Campaigns:</h2>
    <br>
    <% @campaigns = Campaign.all %>
    <% @campaigns.each do |campaign| %>
      <% if campaign.name == current_user.email || current_user.email == "sbhenrichs@gmail.com"%>

        <h3 class="blue lighter text-center"><%= campaign.product %></h3>
        <br>
        <%= campaign.description %>
        <br>
        <%= campaign.date %>
        <br>
        <br>
        <div>
          <% if current_user.try(:email) == campaign.name || current_user.email == "sbhenrichs@gmail.com"%>
            <%= link_to "View Campaign", campaign, class: "btn-link text-center" %>
          <% else %>
            <div class="text-center hundred">
              <a href="/pages/notyours" class="btn-link text-center">View Campaign</a>
            </div>
          <% end %>
        </div>
        <div class="littlespace"></div>

      <% else %>

      <% end %>
    <% end %>
    <div class="space"></div>

    <div class="button-center-con">
      <a href="/users/edit" class="btn btn-primary">Edit Profile</a>
    </div>

    <div class="space"></div>
  </body>
</html>

app/views/campaigns/show.html.erb
<html>
  <head>

  </head>
  <body>
    <h1 class="blue lighter text-center"><%= @campaign.product %></h1>
    <h6 class="text-center lighter">Not sure what to do? <a href="/pages/help" class="btn-link">Click here.</a></h6>
    <br>
    <p class="lighter onetwofive"><%= @campaign.description %></p>
    <br>
    <h3 class="lighter">Additional Information:</h3>
    <br>
    <p><span class="blue">Your Website: </span><%= link_to current_user.website, current_user.website, class: "btn-link-black", target: "_blank" %></p>
    <p><span class="blue">Your Email: </span><%= current_user.email %></p>
    <p><span class="blue">Date Started: </span><%= @campaign.date %></p>
    <p><span class="blue">Product On Amazon: </span><%= link_to truncate(@campaign.productlink, :length => 75), @campaign.productlink, class: "btn-link-black", target: "_blank" %></p>
    <br>

    <div class="button-center-con">
      <%= link_to 'End Campaign', campaign_path(@campaign), class: "btn btn-danger button-center", method: :delete, data: { confirm: "Are you sure? This can't be undone." } %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Force</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
  <script type="text/javascript" src="application.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<nav class="nav">
  <div class="dropdown">
    <div class="sandwhich">
      <div href="#" class="dropdown-toggle sandwich-hover" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <div class="first-line line"></div>
      <div class="second-line line"></div>
      <div class="third-line line"></div>
      </div>

      <ul class="dropdown-menu" id="dropdown-body">
        <li><a href="/links">Home</a></li>
        <li><a href="/pages/how">About</a></li>
        <li><a href="/pages/contact">Contact Us</a></li>
        <% if user_signed_in? %>
        <li role="separator" class="divider visible-xs"></li>
        <li class="visible-xs"><a href="/pages/me"><%= current_user.email %></a></li>
        <li class="visible-xs"><%= link_to "sign out", destroy_user_session_path, method: :delete, class: "btn-link" %></li>
        <% else %>
        <li class="visible-xs"><a href="/users/sign_in">Sign In</a></li>
        <li class="visible-xs"><a href="/users/sign_up">Sign Up</a></li>
        <% end %>
        <% if current_user.try(:email) == "sbhenrichs@gmail.com" %>
        <li role="separator" class="divider"></li>
        <li><a href="/links/new">New Link</a></li>
        <% end %>
      </ul>

    </div>
  </div>
  <div class="links-right hidden-xs">
    <% if user_signed_in? %>
    <a href="/campaigns" class="link-under right"><%= current_user.email %></a><span>/</span><%= link_to "sign out", destroy_user_session_path, method: :delete, class: "link-under right" %>
    <% else %>
    <a href="/users/sign_in" class="link-under right">Sign In</a><span>/</span><a href="/users/sign_up" class="link-under right">Sign Up</a>
    <% end %>
  </div>

  <div class="brand-con">
    <div class="brand"><a href="/links" class="brand-text"><span class="brand-text">blog/force</span></a></div>
  </div>
</nav>

  <div class="container">
    <div class="space">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="first alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
    <% end %>

    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/links/create.html.erb
<html>
  <head>

  </head>
  <body>
    
  </body>
</html>

app/views/links/edit.html.erb
<html>
  <head>

  </head>
  <body>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" %>
    <h1>Update Link</h1>
    <%= form_for @link do |f| %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"Name For Campaign" %>
        <%= f.text_field :product, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :url %>
      <%= f.url_field :url, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
      <%= f.submit :"Update Link", class: "btn btn-primary" %>
      </div>

    <% end %>
    <% end %>
  </body>
</html>

app/views/links/index.html.erb
<html>
  <head>

  </head>
  <body>

    <% if user_signed_in? %>
    <div class="index-space"></div>
      <% @links.each do |link| %>
        <div class="boxes">
          <div class="link-title-con"><span class="link-title"><%= link_to link.title, link, class: "link-title btn-link-black" %></span></div>
          <br>
          <br>
          <div class="link-descrip-con lighter"><span class="link-descrip"><%= link.description %></span></div>
          <br>
          <br>
          <span><%= link_to "View Link", link, class: "link-under" %>
        </div>

        <div class="index-lines"></div>

      <% end %>

    <% else %>
      <% @links.each do |link| %>
      <div class="index-space"></div>
        <% @links.each do |link| %>
          <div class="boxes">
            <div class="link-title-con"><span class="link-title"><%= link_to link.title, link, class: "link-title btn-link-black" %></span></div>
            <br>
            <br>
            <div class="link-descrip-con"><span class="link-descrip"><%= link.description %></span></div>
            <br>
            <br>
            <span><%= link_to "View Link", "/pages/oops", class: "link-under" %>
          </div>

          <div class="index-lines"></div>
        <% end %>
    <% end %>
    <% end %>

  </body>
</html>

app/views/links/new.html.erb
<html>
  <head>

  </head>
  <body>

    <h1 class="blue">New Link</h1>
    <br>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" %>
    <%= form_for @link do |f| %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"Name For Campaign" %>
        <%= f.text_field :product, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :url %>
      <%= f.url_field :url, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
      <%= f.submit :"Create Link", class: "btn btn-primary" %>
      </div>

    <% end %>
    <% end %>
  </body>
</html>

app/views/links/show.html.erb
<html>
  <head>
    <link rel="stylesheet" href="custom.css.scss">
  </head>
  <body>

  <a href="/links" class="btn-link">Back</a>
  <div class="link-whole">

    <div class="image-title-con">
      <span class="show-title lighter"><%= @link.title %></span>
    </div>

    <div class="show-body">

      <div class="show-image">
        <%= image_tag @link.image.url, class: "image-show" %>
      </div>

      <br>

      <div class="show-text">
        <span class="show-description"><%= @link.description %></span>
      </div>

      <br>
      <br>

    <br>

    <p class="text-center show-links">
    <span class="url"><%= link_to "View Product", @link.url, class: "btn-link", target: "_blank" %></span>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" %>
      <span class="blue"> | </span><%= link_to "Update Link", edit_link_path(@link), class: "btn-link" %><span class="blue"> | </span><%= link_to "Delete Link", link_path(@link), method: :delete, data: {confirm: "You sure bud?" }, class: "btn-link" %>
    </p>
    <% else %>

    <% end %>

    <%= form_for :campaign, url: campaigns_path do |f| %>
      <%= f.hidden_field :name, value: current_user.email %>
      <%= f.hidden_field :product, value: @link.product %>
      <%= f.hidden_field :title, value: @link.title %>
      <%= f.hidden_field :website, value: current_user.website %>
      <%= f.hidden_field :productlink, value: @link.url %>
      <%= f.hidden_field :description, value: @link.description %>
      <%= f.hidden_field :date, value: Date.today.to_s %>
      <br>
      <br>
    <div class="button-center-con">
      <%= f.submit :"Start Campaign", class: "btn btn-primary btn-lg button-center" %>
    </div>

    <% end %>

  </div>


  </body>
</html>

app/views/pages/contact.html.erb
<html>
  <head>

  </head>
  <body>
    <h1 class="light blue first">We'd love to talk to you too.</h1>
    <br>
    <p>We hate contact forms, so naturally, we didn't put one in our website. Assuming you have an email, you can email us at info@blogforce.com. If you don't have an email, I can't believe you're reading this, and you can call us at 555-555-5555.</p>
  </body>
</html>

app/views/pages/help.html.erb
<html>
  <head>

  </head>
  <body>
    <h1 class="light blue first">Don't know where to start? We're here to help.</h1>
  </body>
</html>

app/views/pages/how.html.erb
<html>
  <head>

  </head>
  <body>
    <h1 class="blue text-center underline">Blog Force</h1>
    <br>
    <h3 class="blue">About Blog Force</h3>
    <div class="littlespace"></div>
    <p class="packed">
      Blog Force is a web company that delivers Amazon Affiliate deals to provide bloggers and website owners with a way to monetize through native advertising. Man, that last sentence was a mouthful. So basically, it's really cool. We give you all the resources you need to start making money with your blog doing what you do best- creating awesome content for your readers. Want to know how it works? Keep reading.
    </p>
    <br>
    <h3 class="blue">How it Works</h3>
    <div class="littlespace"></div>
    <p class="packed">
      Blog Force is made possible through Amazon. Yay, Amazon! (Don't worry, they're not paying me. Maybe they should.) Basically, we advertise for Amazon, using their affiliate program, and they pay us, but not really. When you make a post, you start generating sales to that product. When you do that, we get a percentage of it. And then we give that back to you. Then, you can do it over again. It's a happy cycle. You can learn more about Amazon's affiliate links at <a href="https://affiliate-program.amazon.com/" class="btn-link" target="_blank">their webiste.</a> If you have any questions about this process, you can email us at info@blogforce.com</a>
    </p>
  </body>
</html>

app/views/pages/list.html.erb
<html>
  <head>

  </head>
  <body>

    <div class="users">
      <% @users = User.all %>
      <% @users.each do |user| %>
        <%= user.email %>
        <span> | </span>
        <a class="btn-link"><%= user.website %></a>
        <br>
      <% end %>
    </div>

  </body>
</html>

app/views/pages/notyours.html.erb
<html>
  <head>

  </head>
  <body>
    <html>
      <head>
      </head>
      <body>
        <h1 class="blue text-center">Sorry, That's Not Yours.</h1>
        <div class="littlespace"></div>
        <h4 class="packed text-center">If it is, you're not in the right account, and you need to <a href="/users/sign_in" class="btn-link">sign in.</a></h4>
      </body>
    </html>

  </body>
</html>

app/views/pages/oops.html.erb
<html>
  <head>
  </head>
  <body>
    <h1 class="blue text-center">Sorry, That's for Members Only.</h1>
    <div class="littlespace"></div>
    <h4 class="packed">We strongly reccomend that you sign up, but since this is our site, you've probaly figured that one out. If you want to make an account for free, you can do that <a href="/users/sign_up" class="btn-link">here.</a> Already have an account?<a href="/users/sign_in" class="btn-link"> Sign In.</a></h4>
  </body>
</html>